version: '3.8'

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        "VARIANT": "18-buster"
        "USER": "node"
        "GROUP": "node"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:project.database
    user: node

  project.database:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: null
